spring:
  data:
    mongodb:
      username: mamor
      password: mamor
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
logging:
  level:
    org:
      springframework: debug
