spring:
  data:
    mongodb:
      username: mamor
      password: mamor
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.maytech.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:com.maytech.ecommerce.kafka.PaymentNotificationRequest
  mail:
    host: localhost
    port: 1025
    username: mamor
    password: mamor
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        startls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8040







