spring:
  profiles:
    active: native
  application:
    name: config-server
  banner:
    location: classpath:banner/banner.txt
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
server:
  port: 8888
logging:
  level:
    org:
      springframework: debug